DROP PROCEDURE spAddCustomer
USE KennelKare


--Script and test the following stored procedures

--1.	Return details of transactions costing less than £50.


--2.	Return Customer details based on the input of a Customer No.
CREATE PROCEDURE spGetCustomerNo @CustomerNo INT 
AS
BEGIN 
SELECT * FROM Customer
WHERE CustomerNo = @CustomerNo
END 

EXEC spGetCustomerNo @CustomerNo = 1005

--3.	Return Customer details based on the input of Customer Surname.
CREATE PROCEDURE spGetCustomerSurname @CustomerSurname VARCHAR(20)
AS
BEGIN 
SELECT Forename, Surname FROM Customer
WHERE Surname = @CustomerSurname 
END 

EXEC spGetCustomerSurname @CustomerSurname = 'Lynch'

--4.	Insert a new Kennel. 
use InTheDogHouse
CREATE PROCEDURE spAddKennel
@Size INT 
AS
BEGIN TRY
	IF(@Size < 1 OR @Size > 4)
	RAISERROR('Kennel size must be between 1 & 4!',11,1)
DECLARE @KennelNo INT 
SELECT @KennelNo = CONVERT (INT,(SELECT TOP 1 KennelNo FROM Kennel ORDER BY KennelNo DESC) + 1)

INSERT INTO Kennel VALUES
(@KennelNo,@Size)

END TRY

BEGIN CATCH 
	DECLARE @ErrorMessage VARCHAR(100)
	SELECT @ErrorMessage = ERROR_MESSAGE()
	PRINT @ErrorMessage
END CATCH

EXEC spAddKennel @Size = 6



--5.	Insert a new Customer.
CREATE PROCEDURE spAddCustomer
@Title VARCHAR(4), @Surname VARCHAR(20), @Forename VARCHAR(20),
 @Street VARCHAR(30), @Town VARCHAR(30), @County VARCHAR(30),
  @PostCode VARCHAR(8), @TelNo VARCHAR(11)
AS
BEGIN TRY
IF(LEN(@Title) < 1 OR LEN(@Title) > 4)
	RAISERROR('Title must be between 1 & 4!',11,1)
IF(LEN(@Surname) < 1 OR LEN(@Surname) > 20)
	RAISERROR('Surname must be between 1 & 20!',11,1)
IF(LEN(@Forename) < 1 OR LEN(@Forename) > 20)
	RAISERROR('Forename must be between 1 & 20!',11,1)
IF(LEN(@Street) < 1 OR LEN(@street) > 30)
	RAISERROR('Street must be between 1 & 30!',11,1)
IF(LEN(@Town) < 1 OR LEN(@Town) > 30)
	RAISERROR('Town must be between 1 & 30!',11,1)
IF(LEN(@County) < 1 OR LEN(@County) > 30)
	RAISERROR('County must be between 1 & 30!',11,1)
IF(LEN(@PostCode) < 1 OR LEN(@PostCode) > 8)
	RAISERROR('PostCode must be between 1 & 8!',11,1)
IF(LEN(@TelNo) < 1 OR LEN(@TelNo) > 11)
	RAISERROR('TelNo must be between 1 & 11!',11,1)

DECLARE @CustomerNo INT 
SELECT @CustomerNo = CONVERT (INT,(SELECT TOP 1 CustomerNo FROM Customer ORDER BY CustomerNo DESC) + 1)

INSERT INTO Customer VALUES 
(@CustomerNo, @Title, @Surname, @Forename, @Street, @Town, @County, @PostCode, @TelNo)

END TRY

BEGIN CATCH 
	DECLARE @ErrorMessage VARCHAR(100)
	SELECT @ErrorMessage = ERROR_MESSAGE()
	PRINT @ErrorMessage
END CATCH

EXEC spAddCustomer
@Title = 'Mr', @Surname = 'Carlin', @Forename = 'Sean', @Street = 'Glenfada', @Town = 'Derry', @County = 'Derry', @PostCode = 'BT49 8XY', @TelNo = '12345678910'



--6.	Return Kennel details priced between a given range of values.


--7.	Return a count of the number of Kennels provided by KennelKare.
--8.	Return the next unique Booking No from the Booking table.
--9.	Return the number of Bookings generated by a Customer.
--10.	Return Booking Details for a given Booking.
--11.	Return the total of each Booking (include Booking date) for a given Customer.
--12.	Update the cost of all Kennels by a given percentage.
--13.	Update the cost of a given Kennel.
--14.	Delete a Customer Booking.
--15.	Delete a given Booking Detail.
--16.	Update the noDays for a given Booking Detail.
--17.	Return a list of Customers who were given a Booking on a given month + year
--18.	Return a list of Customers who were not given a Booking on a given month + year
